version: '3.9'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: pet_api
  web:
    build: .
    command:
             bash -c "python /usr/src/pet/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/pet
    environment:
      - SECRET_KEY=django-insecure-^k@*=+qba!g0m9ukzi&iv-wol%mh6y8int_r49*!9q%hy#f_le
      - API_KEY=1234
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: